export const PROJECT_EN: Record<number, { title?: string; description: string }> = {
  1: {
    description:
      "The villa embodies a subtle fusion of modern minimalism and the spirit of local architecture. Designed with a bioclimatic approach, it offers a fluid transition between urban opacity and interior transparency.\n\nConcept and Volume\nThe project is structured around a clear process of subtraction and opening. A large portico in natural stone wraps the structure, creating a strong visual signal while protecting living spaces from direct sun. The initial volume was carved out to bring in natural light and to optimise cross-ventilation through every room. The scheme sets the warm texture of dressed stone in dialogue with the purity of white render and large sliding glass bays.\n\nIndoor–Outdoor Relationship and Sustainability\nThe spatial layout maximises comfort and privacy, echoing the principles of traditional dwelling, reinterpreted. Ground-floor living rooms open fully onto a linear terrace and a pool, dissolving the boundary with the garden. The living room is defined by contemporary lines, a ceiling with integrated perimeter lighting, and generous, light-filled volumes. The roof incorporates an environmentally responsible approach, with a planned solar terrace for the building’s energy autonomy.\n\nThe project achieves a precise union of radical modernity and subtle references to the local context, offering residential architecture that is both stately, lasting and intimate.",
  },
  2: {
    description:
      "This villa embodies a minimalist, contemporary vision, marrying refined cubic volumes with warm sand tones. The project is organised around strong horizontal lines, creating plays of cast shadow that animate the textured façades. A sheet-of-water pool and large glass bays ensure a fluid transition between the outdoors and the living spaces.",
  },
  3: {
    title: "Kairouan Hotel",
    description:
      "This project develops a distinctive architectural identity on a built area of 580 m², creating a harmonious transition between regional classical codes and high-end minimalism.\n\nVolume and Urban Façades\nThe building’s exterior expression is organised around a rigorous, luminous geometric treatment. The main façade is distinguished by monumental round arches stretching across the upper floors, clad in light textured stone with a pronounced horizontal grain. The pedestrian base opens generously onto the public realm through a sequence of glazed arches and large structural bays, offering complete transparency into the reception spaces. Dark, finely crafted metalwork traces the glazing grid, while a graphic metal mashrabiya section brings a subtle textural vibration to the refined envelope.\n\nInterior Atmospheres and Fit-out\nInside, volumes unfold with a sense of theatre, privileging noble materials and generous perspectives. The grand double-height hall is organised beneath a contemporary cascading sculptural chandelier. The polished marble floor deploys a complex geometric pattern that guides visitors toward a monolithic reception desk in fluted white marble, heightened with brushed brass. The project includes large meeting and conference rooms with carefully considered acoustics, characterised by rhythmic technical ceilings (luminous coffers or suspended waves), arched glazing and warm wall finishes in vertical timber battens or dark wood panelling.\n\nThe Kairouan Hotel revisits the heritage of the classical arch through a contemporary, refined prism, where the nobility of stone, marble and wood composes a place of stay of timeless sophistication.",
  },
  4: {
    title: "Rabat Mixed-Use Building",
    description:
      "The architectural concept of the Rabat Mixed-Use Building rests on a rigorous bioclimatic approach, expressed in a contemporary linear structure fully integrated into its urban fabric.\n\nSiting and Urban Morphology\nThe project uses the site’s regulatory and environmental constraints to create an airy, dynamic block. The main volume is sculpted by a succession of planted interior patios that ensure optimal sunlight and excellent natural ventilation for the dwellings. The building maintains a generous landscaped setback from the major roads, while opening onto the city through a continuous commercial ground floor sheltered under wide cantilevers. Interior courtyards house pyramidal light wells that visually and thermally connect basement parking with the gardens above.\n\nFaçades and Technical Devices\nThe outer envelope expresses a sober modernity, paced by integrated technical solutions. A metal-rail brise-soleil system incorporates planters and evergreen climbing plants, protecting the south façade from summer radiation while tempering the impact of the prevailing north-west winds. Walls alternate between light render, large glass panels for commercial frontage, and delicate geometric screens inspired by traditional mashrabiyas. The upper floors step back as attics, underlined by long hanging planters that crown the building with a vegetal frieze.\n\nIn short, the Rabat Mixed-Use Building succeeds in combining urban rationalism with passive comfort, where the rhythm of planted façades and the integration of patios offer a lasting response to mixed-use requirements.",
  },
  5: {
    description:
      "This villa embodies a contemporary, eclectic vision, marrying generous double-height volumes with earthy, golden tones that are textured and warm. The project is organised around strong, structuring lines, where carefully integrated lighting highlights timber finishes and wall artworks. A pool integrated into the architecture, visible through large glass bays, ensures a fluid transition between the living space and the outdoors. The two-level interior is organised around a monumental staircase, privileging the transparency of a glass mezzanine and the nobility of materials.",
  },
  6: {
    title: "Sidi Guith Mosque",
    description:
      "The renovation of Sidi Guith Mosque was born of a clear ambition: to modernise the interior while preserving the soul, solemnity and spiritual vocation of the place.\n\nClarity and Spatial Fluidity\nThe architectural intervention is organised primarily around the search for light and the liberation of volume. A subtly integrated mezzanine was rethought to structure the prayer space without weighing it down. Transparent glass balustrades lighten the upper level and allow natural light to flow freely through the entire volume.\n\nA Dialogue between Minimalism and Tradition\nThe aesthetic approach relies on restraint in order to magnify what already exists. A palette of light tones and refined lines establishes a serene, timeless and calming atmosphere. The neutrality of the new walls serves as a setting for the delicacy of traditional details, from calligraphic friezes to the majesty of the large crystal chandeliers.\n\nBy combining contemporary fluidity with respect for the sacred, this rehabilitation offers worshippers a harmonious, airy and welcoming place of prayer, designed to enhance comfort and elevate contemplation.",
  },
  7: {
    description:
      "The Dar Cherif project in Kairouan is an exceptional rehabilitation, transforming a heritage house into a prestigious living and reception space. The intervention builds a harmonious bridge between the restraint of contemporary minimalism and the richness of local Arab-Muslim architectural detail.\n\nFaçade and Urban Integration\nThe exterior architecture preserves the spirit of Kairouan’s great houses while asserting its new vocation. A façade paced by large, refined arcades combines traditional warm-toned render with discreet glass balustrades. Monumental entrances, marked by large sculpted blue timber doors, are crowned by a fluid calligraphic sign carved into the stone.\n\nThe Central Patio: A Luminous Event Space\nThe great heart of the house has been rethought to host events and receptions of scale, while remaining protected from the elements. A contemporary glass-roof structure bathes the patio in daylight and opens onto the night sky. A monumental aerial scenography combines immense white voile drapes, sparkling light garlands and hanging floral compositions. A striking contrast of textures sees the modernity of the glass roof and white structures in dialogue with a vast wall of zellige in vibrant geometric patterns and a large azure-blue mashrabiya.\n\nInterior Salons and Spaces of Rest\nThe interior rooms offer an intimate, high-end atmosphere, suited to conviviality and tasting. Reinterpreted Tunisian-style salons combine cobalt-blue built-in banquettes with sculpted wall niches incorporating subtle backlit calligraphic inscriptions. A theatrical play of shadow and light, created by wall lights and engraved copper lanterns, projects complex geometric patterns onto raw plaster walls. Refined joinery details, notably partitions and porticoes in dark wood richly carved with traditional arabesques, separate service spaces and artisan ceramic basins.",
  },
  9: {
    description:
      "This villa perfectly illustrates our modern, refined reinterpretation of traditional Mediterranean architecture. The project starts from an immaculate white volume, delicately carved out to form an intimate patio and capture natural light. Large arches and glass bays create a direct, fluid link between the living spaces and the pool. The interior layout is harmonious and single-storey, naturally separating vaulted reception rooms from bedrooms set further back.",
  },
  10: {
    description:
      "The architectural concept of the rural guesthouse in El Oueslatia rests on an environmentally responsible, vernacular approach. Set on a 750 m² plot with a built area of 100 m², the project sits organically at the heart of a preserved olive grove.\n\nSiting and Outdoor Life\nThe spatial layout privileges disconnection, conviviality and respect for the landscape. Structures are carefully dispersed across the site and linked by a fluid network of winding paved paths that thread through the vegetation. A large open timber pavilion, crowned with a traditional thatched roof, hosts a summer lounge organised around a substantial stone hearth and airy drapes. The architecture recedes before nature, offering direct panoramic views of the surrounding rows of olive trees.\n\nLodge Architecture and Materials\nThe buildings reinterpret the codes of rural dwelling with contemporary sensitivity. The living pavilions adopt a sober volume, characterised by asymmetrical pitched roofs and a tall central chimney in rustic stone. Envelopes marry traditional light render with sections of dark timber cladding, paced by slender vertical openings and small private gravel terraces. The main dining pavilion is given large corner glass bays and extends into a terrace sheltered under a timber pergola, creating a gentle transition for outdoor dinners facing the sunset.\n\nThe project offers a peaceful, respectful refuge, where the use of stone, wood and thatch celebrates the authenticity of Tunisian rural life.",
  },
  11: {
    title: "Headquarters of the Regional Equipment Directorate, Errachidia",
    description:
      "The headquarters of the Regional Directorate of Equipment, Transport, Logistics and Water of Drâa-Tafilalet in Errachidia follows a bioclimatic, contemporary approach. The architecture proposes a strong dialogue between the oasis identity of the region and the functional requirements of a modern public building.\n\nUrban Insertion and Volumetric Composition\nThe overall organisation of the site optimises the 6,350 m² plot at the north-west entrance to the city, along national road N13. A morphology broken into distinct blocks, articulated around interior patios, favours natural ventilation and filtered light. A textured ochre-terracotta façade takes up the tones of the local earth while asserting refined geometric lines and massive volumes anchored in their setting. Solar-protection devices — modernised mashrabiyas in perforated brick and deep recessed balconies housing planted troughs — complete the envelope. An integrated landscape scheme stages alignments of palm trees and paved paths linking peripheral parking to the various entrances.\n\nInterior Fit-out and Inclusive Accessibility\nThe interior privileges clear circulation, noble materials and comfort for all users. A monumental glazed reception hall, bathed in soft zenithal light, combines a dark floor finish with a two-material reception desk in veined black marble and timber slats. A large open-air central patio, conceived as an oasis of coolness with lawn, palms, shrubs and a central fountain, offers an optimal rest space for staff and visitors. Universal accessibility is expressed through tactile paving and textured rubber mats set into the floor, guiding visually impaired visitors independently toward the various administrative offices.",
  },
  13: {
    title: "Dramatic Arts Centre",
    description:
      "A Fluid, Structured Spatiality\nThe building asserts itself through a remarkable volumetric duality: an imposing cylindrical body with arcades articulates harmoniously with refined cubic volumes housing the performance hall. True beating heart of the project, the grand entrance hall and foyer distribute training spaces, exhibition areas and the main auditorium in a clear, rational way. Vast round-arched openings and glazed façades break with the traditional rigidity of administrative buildings, flooding interiors with generous natural light while symbolising the institution’s transparency toward the public realm.\n\nContextual Anchoring and Noble Materiality\nThe exterior envelope, characterised by white and pale sand tones, sits perfectly with the Tunisian climate and landscape. The outer design is strongly dynamised by textured local-stone cladding, dressing monumental porches and load-bearing structures to root the project in its territory, and by gilded, chiselled mashrabiyas crowning the circular volume and the stage tower, delicately filtering light while paying homage to artisanal heritage.\n\nAn Integrated, Living Programme\nOutside as inside, the user’s path has been designed to encourage encounter and artistic expression. A central half-moon landscaped patio, with a fountain and lush planting, offers a space of rest and coolness for artists and visitors. A multi-purpose sports court at the rear of the plot reinforces the centre’s inclusive, dynamic vocation for young people.\n\nThis work signs a committed, lasting and welcoming public architecture, giving the city of Siliana an essential visual, cultural and civic landmark.",
  },
  14: {
    title: "Rebai School",
    description:
      "This school project, developed over two levels (ground + 1), proposes a contemporary reinterpretation of local architecture. The building is fragmented into several distinct volumes articulated around courtyards and central patios.\n\nBioclimatic Architecture and Living Spaces\nThe spatial organisation emphasises thermal comfort and quality of life for users. Patios and interior courtyards, conceived as true green lungs, integrate vegetation to create a favourable microclimate. A natural regulation system guarantees passive cooling, optimal ventilation and a generous supply of daylight within circulations and classrooms. A large central paved courtyard serves as the functional heart of the school, encouraging gathering and cohesion in the open air.\n\nExterior Envelope and Environmental Commitment\nThe façade design combines technical performance, playful aesthetics and urban insertion. A fragmented volume in light tones, characterised by refined façades, softens the visual impact of the building in its surrounding fabric. Openings enlivened by touches of bright colour contribute to the school’s joyful identity while structuring the rhythm of the façades. An environmentally responsible and inclusive approach offers a fluid path, fully secure and accessible to every pupil, for a lasting learning environment.",
  },
  15: {
    title: "Chweyhia Town Hall",
    description:
      "The fruit of a close architectural collaboration, the new town hall of Chweyhia proposes a contemporary, solemn and human reinterpretation of local institutional architecture. Developed over two levels (ground + 1), this civic project was conceived to embody the values of transparency, accessibility and public service within the community.\n\nAn Open, Luminous Spatiality\nThe building asserts itself through refined geometric volumes articulated around a large double-height central hall. True beating heart of the project, this space of welcome and civic exchange distributes the various services in a clear, rational way. Full-height glass bays break with the traditional rigidity of administrative buildings, flooding interiors with generous natural light while symbolising the institution’s transparency toward the public realm.\n\nContextual Anchoring and Noble Materiality\nThe exterior envelope, characterised by pale sand tones, sits perfectly with the climate and landscape of Kairouan. The outer design is dynamised by textured local-stone cladding and dark, elegant joinery that underlines the rigour of the lines. Inside, the user journey is heightened by noble, lasting materials: marble flooring confers solemnity and durability in the face of heavy use, while the warm wood of reception counters and contact zones softens the atmosphere, offering an environment of listening and work that is both serene and ergonomic.\n\nThis work signs a committed, lasting and welcoming public architecture, giving the municipality of Chweyhia an essential visual and civic landmark.",
  },
  16: {
    title: "Tax Office in Cherarda",
    description:
      "This architectural project occupies a highly strategic site in Cherarda, orienting its main building toward the GP2, the major road linking Kairouan to Gabès. The adopted parti proposes a harmonious dialogue between functionality and restraint by articulating two ground-plus-one volumes inscribed in pure geometric forms (circle, rectangle and triangle). In the foreground, the administrative volume houses the tax office on the ground floor and the control office above, asserting its institutional role through public accesses clearly signalled from the main road. Set back, the second volume houses staff dwellings (reserved for the receiver on the ground floor and the office head above), served by two distinct car parks. These private accesses are ingeniously placed in opposition to guarantee privacy and avoid overlooking. Aesthetically, the façade treatment combines a refined contemporary vocabulary with the use of traditional Kairouan brick, heightened by large chiselled white mashrabiyas and glazed panels that flood the citizens’ relations office with light, creating a public facility that is at once modern, secure and rooted in its local heritage.",
  },
  17: {
    description:
      "The rehabilitation of Souk El Mouajil in Kairouan sets out to restore life to a historic space of artisan production and sale, long neglected and altered by time. The intervention rests on a careful alliance of heritage restoration and contemporary fit-out, transforming the place into a dynamic economic, cultural and tourist hub.\n\nTechnical Restoration and Architectural Identity\nThe architectural approach privileges the preservation of the building’s morphology and structural authenticity while integrating modern technologies. A faithful repair of the vaults and brick structures highlights the original texture of Kairouan brick while consolidating the covered nave. Natural light is optimised by oculi and zenithal lanterns pierced through the vaults, spreading a soft clarity and limiting the need for artificial lighting during the day. Environmentally responsible technical integration is characterised by discreet modern sanitation solutions and photovoltaic panels placed on the outer flat roofs to ensure the site’s energy autonomy.\n\nInterior Fit-out and New Uses\nEntirely rethought, the interior is structured as a fluid path celebrating local craft. Reinterpreted artisan shops and workshops, paced by large minimalist glass openings that sit harmoniously beneath the historic arcades, stand alongside a traditional café and convivial zones, fitted with low furniture and built-in banquettes, creating professional meeting spaces and rest areas for visitors. An art gallery and exhibition spaces combine the charm of original stone-paved floors with a refined contemporary scenography, ideal for showcasing the region’s creations.",
  },
  18: {
    title: "Landscaping and Enhancement of the Outdoor Spaces of Kairouan Municipal Pool",
    description:
      "This urban requalification project is a direct response to the site’s structural and social issues, aiming to improve and enrich both the programme and the existing space of Kairouan’s municipal pool.\n\nSports Infrastructure and Dynamic Practices\nConceived as a vector of social cohesion answering strong pressure on neighbourhood facilities, the complex modernises the site’s offer through complete sports infrastructure. A modern racket hub integrates a technical padel court surrounded by glazed structures and appropriate fencing, introducing a new dynamic practice. Diversified collective courts bring together basketball pitches, a city stadium and a multi-sports plateau with regulatory, colourful markings to maximise use of space. An outdoor fitness area, dedicated to strength training, calisthenics and wellbeing, is laid out on a thematic resilient surface.\n\nTechnical, Landscape and Functional Arrangement\nFrom the approach to the site, the project reveals a strong technical and landscape approach to guarantee an inclusive, lasting space for training and rest. Structural protection of the ground, marked by extensive mineral paving, ensures the durability of foundations against rainwater infiltration. The enhancement of existing planting preserves the visual identity and shade of historic palms along the paths. Comfort and management equipment harmoniously integrates a new public sanitary block, large textile shade structures for solar protection, and a perimeter fence for optimal, secure management of flows.",
  },
  19: {
    title: "JSK Kairouan Sports Complex",
    description:
      "This multifunctional complex is intended as a true showcase of modernity for the historic club Jeunesse Sportive Kairouanaise (JSK), combining the club’s visual identity with respect for the city’s architectural character. Conceived as a structuring, economically autonomous urban hub, the project deploys an ingenious structural idea: spanning vast sports spaces in order to integrate, with lightness, residential and commercial functions above.\n\nThe ground floor is animated around a vibrant synergy, designed for social cohesion, comprising the JSK Store, neighbourhood shops and dining spaces, opening onto complete facilities such as a homologated indoor arena and outdoor pitches (football, mini-football, padel and a play area). In the basement, an aquatic hub with a semi-Olympic pool and a sports-medicine centre complete this elite-preparation offer. The upper levels house the club administration, a large fitness hall, and a residential block over three floors for athlete accommodation or rental use.\n\nThought both as a regional centre of excellence able to host intensive training camps and as a genuine intergenerational place of life, the project embodies the will to offer high-level infrastructure while guaranteeing the financial continuity and community reach of JSK.",
  },
  20: {
    description:
      "A Multidisciplinary, High-Performance Sports Offer\nThe heart of the architectural programme rests on the technical quality and diversity of its outdoor facilities, distributed in a rational way. The aquatic space includes a semi-Olympic training pool with covered stands, offering ideal conditions for competition and learning. Team sports benefit from fully fenced synthetic-turf football pitches and modern basketball courts equipped with high-performance night lighting. Racket sports are equally served, with tennis and padel courts protected by light mesh structures that sit discreetly in the landscape.\n\nThe Central Hub: Conviviality and Services\nBeyond its athletic vocation, the complex is intended as an intergenerational, social place of life, structured around a contemporary reception and administration building. The main pavilion develops over several levels with an open structure and large glass bays. It houses terrace dining spaces overlooking an amenity pool animated by water jets, creating a cooling microclimate. The adjacent recreational zone offers a secure children’s play area on a sand bed, allowing families to rest immediately beside the terraces. A network of landscaped paths crosses the entire site, offering a shaded, winding jogging route among trees, flower beds and clipped shrubs.\n\nEnvironmental Responsibility and Logistics\nInfrastructure management integrates a strong environmental dimension. The large-capacity landscaped car park is entirely covered with photovoltaic shade structures. These structures serve a double role: protecting vehicles from intense solar radiation while generating clean energy, ensuring partial energy autonomy for the complex’s energy-intensive equipment, notably lighting and pool filtration systems.",
  },
  21: {
    title: "Redevelopment of the Surroundings of La Rahba",
    description:
      "This ambitious urban requalification project, driven by the “We Love Kairouan” association, aims to transform the historic surroundings of La Rahba into a hub of tourism, culture and commerce of excellence. From the approach to the site, the scheme reveals a deep restructuring of public space through the creation of a vast pedestrian square, punctuated with greenery, public benches and energy-efficient lighting, all integrating an ecological rainwater-recovery system. Designed to enhance the city’s heritage identity, the programme proposes a bold conversion of historic buildings: Zaouia El Ouhichia is reinvented as an art gallery, Dar El Ouhichi as a charming guesthouse, while the El Bradâa space is revitalised by the creation of a museum, accompanied by shops transformed into cultural cafés.\n\nIn order to eradicate visual chaos and considerably improve the living environment, a complete reorganisation of logistics and mobility is implemented. This includes a revision of circulation plans, strict regulation of delivery hours, parking for vehicles and bicycles, and a video-surveillance network to ensure safety. The new tourist circuit, which brings the Medina ramparts into prominence, is also supported by the creation of a new commercial hub guaranteeing the economic continuity of the traditional market. Finally, this optimised path is conceived at the scale of the city through the integration of a light-metro line, ensuring fluid public transport and extending this urban and tourist dynamic as far as the famous Aghlabid Basins.",
  },
  22: {
    title: "Restructuring and Enhancement of the “Pains Tabouna” Outskirts",
    description:
      "The fruit of a thorough urban reflection, the restructuring of Kairouan’s peripheral belt proposes a contemporary, ordered and human reinterpretation of public space and local commerce. Deployed linearly along a strategic axis, this civic project was conceived to embody the values of transparency, accessibility and public service while fighting unplanned development within the community.\n\nAn Open, Luminous Spatiality\nThe layout asserts itself through a refined geometric grid articulated around a large shared central square. True beating heart of the project, this space of welcome and civic exchange distributes the various commercial modules in a clear, rational way. Light structures and vast contemporary pergolas break with the traditional rigidity of roadside alignments, flooding shared spaces with filtered natural light while symbolising the institution’s openness toward the public realm.\n\nContextual Anchoring and Noble Materiality\nThe exterior envelope of the kiosks, characterised by sand and light-wood tones, sits perfectly with the climate and landscape of Kairouan. The urban design is dynamised by textured cladding, dark elegant metal structures, and timber screens with geometric patterns that underline the rigour and modernity of the lines while preserving a traditional touch. Within the intervention zones and along the paths, the user experience is heightened by noble, lasting materials: stone paving confers solemnity and durability in the face of heavy pedestrian use, while the warm wood of sales counters and café terraces softens the atmosphere, offering an environment of listening and conviviality that is both serene and ergonomic.\n\nA Public, Inclusive Programme\nDesigned for every generation, the site integrates essential living spaces that enrich the civic journey. A landscaped, secure play area offers families a space of rest and conviviality amid lawned zones. A public services and sanitary pavilion guarantees the comfort and hygiene indispensable to the viability of this destination.\n\nThis work signs a committed, lasting and welcoming public architecture, giving the municipality an essential visual and civic landmark.",
  },
  23: {
    description:
      "This new-generation industrial project is a true architectural response to contemporary production requirements, providing BODOCHIM with a logistics and tertiary complex that is both rational and modern. From the approach to the site, the project reveals a readable functional duality, marked by an administrative volume with immaculate façades that favour natural light, subtly contrasted by dark grey metal cladding and a textured entrance totem. Conceived as a high-performance working tool answering intense logistics flows, the complex deploys in the background vast industrial halls with classical roofs, equipped with multiple sectional doors suited to heavy-goods-vehicle gauges. At the heart of this rigorous organisation, designed to optimise loading manoeuvres and container transit, functional outdoor arrangements are softened by palms offering a high-quality landscaped welcome. The ensemble, enclosed by a perimeter protection wall with a wide sliding gate for secure access management, constitutes a true structuring activity hub, expressing the company’s will to combine high industrial performance with a lasting brand image.",
  },
  24: {
    title: "Mixed Industrial Complex – Industrial Zone, Tunis Road, Kairouan",
    description:
      "An Architectural Synergy in the Service of Performance\nThis contemporary industrial project is the fruit of a close collaboration among three architects, brought together to fuse their expertise and formulate a high-level architectural response to current production requirements. Beyond the managerial and technical challenge of this co-design, the group met a major conceptual challenge: to conceive an ultra-performant working tool, able to adapt and reconfigure immediately to host any type of future industrial activity.\n\nA Strong, Memorable Visual Identity\nFrom the approach to the site, ideally located on the strategic Tunis Road axis, the complex reveals an assertive visual and geometric identity. The design is marked by a vast bright-yellow horizontal band that underlines the administrative block, contrasting with the rigour of dark ribbed metal cladding at the crown. At the heart of this functional arrangement is a bold play of volumes in which this yellow canopy folds sculpturally down to the ground, creating a strong visual landmark in Kairouan’s industrial landscape.\n\nLogistics Infrastructure and Flexibility of Flows\nDesigned to answer intense operating flows, the space offers complete, fluid logistics infrastructure. The main access is crowned by a majestic portico, with a red, clearly signed guard post for access control, and a wide open-work sliding gate. A vast rear service yard, dimensioned for heavy utility-vehicle circulation, is equipped with a raised unloading dock.\n\nThanks to its optimised structural grid and spatial modularity, this enclosed ensemble constitutes a model of lasting, ergonomic and evolutive industrial architecture, ready to accompany the development of any enterprise.",
  },
  25: {
    title: "Baraka Building",
    description:
      "The Concept: Between Modernity and Tradition\nLocated on one of Kairouan’s most prestigious axes — Avenue Abou Zamaa El Balaoui, immediately beside the mausoleum — this project stands as a link between history and contemporaneity. The façade fuses modern lines and materials with the codes of local heritage: the authenticity of traditional Kairouan brick and the subtlety of the mashrabiya.\n\nOne Site, Two Proposals (ground + 4)\nTo reveal the full potential of this strategic site with a commercial ground floor, the project unfolds in two architectural visions:\nProposal 1 | The Tertiary Hub (Offices): Luminous, modular and high-performance professional floors, benefiting from a prestigious address to dynamise economic activity.\nProposal 2 | The Residential Setting (Housing): High-end urban apartments where the mashrabiya filters light and preserves residents’ privacy at the heart of the city.\n\nStrengths\nUrban Dialogue: An architecture that respects and enhances its unique historic context.\nLocal Identity: Traditional brick reinvented in a contemporary language.\nFlexibility: Proof that the same place can offer two equally strong and coherent answers for living or working.",
  },
  26: {
    title: "Fleur d’Acacia Residence",
    description:
      "Located in Sahloul 4, a high-density, highly competitive residential neighbourhood, Fleur d’Acacia Residence relies on a strong visual identity to stand out. The project meets a double challenge: to enhance a steeply sloping site and to exploit a through plot offering two façades on two distinct streets.\n\nThe building skilfully absorbs the level change through an optimised base. This dual-purpose ground floor houses both dynamic commercial premises and well-integrated private residential spaces.\n\nTo distinguish itself from the competition, the design proposes a rigorous, asymmetrical play of volumes on both façades. The purity of white render is associated with the nobility of beige stone and wood-effect inserts, bringing warmth and standing. The alternation of deep loggias, projecting balconies and a vertical glazed cleft sculpts the shadows, protects from the Sahel climate and confers on the whole an elegant lightness that immediately captures the eye.",
  },
  27: {
    title: "Sienna Building",
    description:
      "This contemporary architecture project proposes the design of a modern mixed-use building, combining tertiary spaces on the ground floor with offices on the upper floors.\n\nVisual Identity and Façade Composition\nThe exterior envelope is distinguished by a rigorous geometric treatment and a contrasted choice of materials. A warm vertical insert, characterised by a beige wood-effect textured cladding, rises the full height to break the monotony of the white render and visually stretch the structure. A play of projecting frames, in the form of asymmetrical white rectangular volumes surrounding the windows, creates dynamic relief while serving as integrated planters for hanging vegetation. Discreet linear lighting, materialised by recessed vertical LED bands, underlines the fracture lines of the façade and enhances the volume at nightfall.",
  },
  28: {
    title: "Victoria Building",
    description:
      "The residential project is organised around a neoclassical language and a carefully considered treatment of verticality.\n\nPrincipal Characteristics\nFaçades and Ornament: Pure-white walls integrate structural classical pilasters and are crowned by wide projecting cornices. Bays and Contrasts: Dark joinery and the worked ironwork of the balconies contrast with the arched treatment of the upper-level bays. Loggias and Volume: Successive setbacks and deep loggias sculpt the volume, creating sheltered outdoor spaces while lightening the mass of the building. Base and Access: The building sits on a robust plinth that integrates garage ramps and highlights a raised main entrance.\n\nIn short: A collective residential composition that combines classical proportions and refined details to guarantee a stately insertion into the urban fabric.",
  },
  29: {
    description:
      "Medical Building, Ground + 3: Health Excellence & Standing\nThis project redefines medical architecture through a humanist, high-end approach, designed to stand out strongly from the competition.\n\nA Stately, Biophilic Façade\nThe building’s identity is distinguished by large glass bays that flood interiors with light, dressed by generous integrated planters. These hanging troughs protect the privacy of consulting rooms while offering a unique visual signature — vegetal and cooling — in an urban setting.\n\nA Rigorous Functional Programme\nGround floor: A modern, fluid and accessible medical analysis laboratory.\n3 floors: Consultation rooms optimised for different specialties.\n\nA Privileged Patient Experience\nInside, the design breaks with cold clinical codes. Waiting rooms adopt the standards of high-end lounges (wood cladding, indirect light, enveloping furniture) to transform the care journey into a serene, confidential and highly valued experience for practitioners.",
  },
  30: {
    title: "Villa Babylon: Contemporary Hanging Gardens",
    description:
      "This project strongly embodies our modern, minimalist vision of residential architecture. Named Villa Babylon in reference to the planters that run along the floors like a cascade of hanging gardens, the house reinvents the relationship between nature and building.\n\nConceived from a simple block, the volume is subtly sculpted by horizontal lines and carved out to let in natural light, while opening the spaces widely onto the outdoors. The interaction between vast glass bays and an impressive water cascade, anchored in a stone veil, weaves a direct, fluid link between the living rooms and the amenity pools.",
  },
};
